name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Target
      run: rustup target add wasm32-unknown-unknown 
    - name: Build
      run: cargo build --verbose
